services:

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/usr/local/tomcat/logs
    develop:
      watch:
        - action: rebuild
          path: .
