services:

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - src/main/resources/.env
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/usr/local/tomcat/logs
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - .git
            - .idea
            - .vscode
            - .DS_Store
            - logs
            - target
